### ISSUE TITLE
Facility to add specific GN configuration (geonet:info)

### ISSUE THREAD

**Issue by eblondel** [GeoCat/geonetwork-2#1]
Hello, with Geonetwork 2 and 3, for the current web-services API (and not the new beta REST service), interacting with the API requires to have geonet:info retrieved in service responses. It is disabled by default in the Geonetwork installation. I'm building a client for Geonetwork API (https://github.com/eblondel/geonapi/issues/1) and I would like to set-up CI tests for the GN service operations, for QA purpose. Is there a way I could configure the geonetwork-2 docker to have geonet:info enabled when I start geonetwork?

Here is similar issue i've created for the official docker-geonetwork, while trying to set-up some integration tests with GN3: https://github.com/geonetwork/docker-geonetwork/issues/8

Thanks a lot in advance for your advice,
Best,
Emmanuel

**Comment by doublebyte1** [comment]
Hi @eblondel . This image is marked as **_deprecated_**: we are no longer maintaining it. Let us keep the discussion the official image repository.

**Comment by eblondel** [comment]
Thanks for your reply. BTW: ``Only use this if you want to try the old version of geonetwork`` The official image repository doesn't provide any way to install GN2. As said in the other ticket, I need backward compatibility with GN2, considering there are still many institutions that keep using GN2. Is an image for GN2 envisaged in the official image repository? I don't think so...
Let's keep discussing in the other ticket then...

**Comment by doublebyte1** [comment]
I understand your point @eblondel , we also have a few customers which still use version 2 of Geonetwork: we are just **not** maintaining this version on docker hub, and there are no plans of creating an official image of Geonetwork 2, either. 
If you want, feel free to hire us on a support contract, and we will implement whatever missing features you need on the Geonetwork2 image.
